### ISSUE TITLE
Re-clone crates.io-index when squashed

### ISSUE THREAD

**Issue by panzerballett** [panamax-rs/panamax#3]
my sync stopped working a few days ago with the message:

```
Merging crates.io-index repository failed: GitError(Error { code: -3, klass: 22, message: "no merge base found" })
You will need to sync again to finish this download.
```

the error presists; re-running `panamax` does not help.

could i just `cd` to `crates.io-index/.git` and do a `git fetch --all` (or something more advanced like `git fetch origin "+refs/heads/*:refs/heads/*" "+refs/tags/*:refs/tags/*" "+branches/*:branches/*" --prune --tags --update-head-ok`)?

**Comment by panzerballett** [comment]
i ended up with a brute-force solution for the time being: i renamed `crates.io-index/.git` to `crates.io-index/.git_orig` and ran panamax - which reported no error this time and `crates.io-index/.git`was recreated. what is bothering a bit is that when i compare the size of the original git with the freshly created one i get:

```
crates.io-index$ du -sh .git*
24M     .git
243M    .git_orig
```

**Comment by k3d3** [comment]
Ah, shoot. Looking into this, I think I know why:

https://github.com/rust-lang/crates.io-index/commit/5f2e23e89e97bedc21250a4c57216dd2f6182a5e#diff-49e56763f72df36758394d5213f4bd90

Every once in a while, the maintainers will collapse the crates index in order to reduce the size (as you can see the fairly substantial difference here), and in doing so they end up effectively rebasing the whole repo. This means that directly pulling from it should no longer work, until it is re-cloned.

Unfortunately I don't have any idea how to actually handle this scenario, and I don't know if deleting and re-cloning is a viable option. Does anyone else have any ideas?

**Comment by panzerballett** [comment]
it would be nice of the maintainers of the repository to publish a file that contains the hash of the root commit of their current git repo... this information could then be used to determine if the git repo has been rebased or not.

**Comment by panzerballett** [comment]
>  I don't know if deleting and re-cloning is a viable option.

i have been doing that for quite some time now and it seems to work...

**Comment by k3d3** [comment]
Oh, good to know! I could probably use that as a strategy whenever a pull fails for some reason.

**Comment by panzerballett** [comment]
i would appreciate that very much. thanks a lot! unfortunately i am not yet proficient enough in rust to help... sorry.
