### ISSUE TITLE
Download only specific crates

### ISSUE THREAD

**Issue by ItsAleph** [panamax-rs/panamax#63]
Is it possible to download only speciefic crates, e.g., `panamax sync my-mirror --crates="serenity,rand,songbird"`?

**Comment by k3d3** [comment]
Unfortunately it's not currently possible to only download specific crates. It would be pretty cool to have Panamax support this in the future, however doing so would be a pretty big feature, due to Panamax needing to implement two things:

1) The ability to reach into an existing crate archive file's `Cargo.toml` to grab all of its dependencies recursively, and

2) The ability to serve a `crates.io-index` repository that does not match with the upstream repository, in order to match up with only the crates on the mirror.

Between the large effort required to implement it, and the fact that it's not something I personally need, I don't believe I'll be getting around to implementing this functionality any time soon sadly.

At the same time though, this is an interesting feature and I'd be open to PRs for it.

**Comment by ricked-twice** [comment]
@k3d3 As a first step, it could be good to download only crates passed as arguments by user and not their dependencies?
Because such a feature would put basic logic for this feature, but also to correct #64.

**Comment by k3d3** [comment]
This should be solved with the new feature added in #71.
