### ISSUE TITLE
Not working over SSH

### ISSUE THREAD

**Issue by mainrs** [panamax-rs/panamax#75]
I usually set `net.git-fetch-with-cli=true` inside `.cargo/config.toml`. However, this does not work with panamax. Taking a look at the [documentation](https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli) reveals that `CARGO_NET_GIT_FETCH_WITH_CLI` can also be used. But that does not work for panamax as well.

**Comment by k3d3** [comment]
That makes sense, as Panamax only exposes an HTTP(S) server for interacting with git, rather than SSH.

I'm unfortunately not experienced with integrating SSH with git, so I'm not sure how to do that within Panamax. Perhaps using the `thrussh` library would be useful, but I'm not sure where to go from there.

**Comment by mainrs** [comment]
Do you rely on external commands within panamax? Or do you use dedicated libraries to interact with git and cargo?

**Comment by k3d3** [comment]
I believe git is the only external dependency, and that's just for serving: https://github.com/panamax-rs/panamax/blob/master/src/serve.rs#L294

Basically Panamax acts as a CGI gateway to `git http-backend`.

**Comment by k3d3** [comment]
Hey, are you still having this issue @mainrs ?

**Comment by k3d3** [comment]
I'm going to close this issue for now. Feel free to reopen it if it's still an issue for you.
